keywords = {
# Generic suspicious
    'idp.': 25,
    'login': 25,
    'log-in': 25,
    'sign-in': 25,
    'signin': 25,
    'account': 25,
    'verification': 25,
    'verify': 25,
#    'webscr': 25,
    'password': 25,
    'credential': 25,
    'support': 15,
    'activity': 25,
    'security': 25,
    'update': 25,
    'authentication': 25,
    'authenticate': 25,
    'authorize': 25,
#    'wallet': 25,
    'alert': 15,
#    'purchase': 25,
    'transaction': 25,
    'recover': 25,
    'unlock': 25,
    'confirm': 20,
#    'live': 15,
#    'office': 15,
    'service': 15,
    'manage': 15,
    'portal': 15,
    'invoice': 15,
    'secure': 10,
    'customer': 10,
    'client': 10,
    'bill': 10,
    'online': 10,
    'safe': 10,
    'form': 10,

# Apple iCloud
#    'appleid': 70,
#    'icloud': 60,
#    'iforgot': 60,
#    'itunes': 50,
#    'apple':30,

# Email
#    'outlook': 60,
#    'office365': 50,
#    'microsoft': 60,
#    'windows': 30,
#    'protonmail': 70,
#    'tutanota': 60,
#    'hotmail': 60,
#    'gmail': 70,
#    'google': 70,
#    'outlook': 60,
#    'yahoo': 60,
#    'google': 60,
#    'yandex': 60,

# Social Media
#    'twitter': 60,
#    'facebook': 60,
#    'tumblr': 60,
#    'reddit': 60,
#    'youtube': 40, # some false positives
#    'linkedin': 60,
#    'instagram': 60,
#    'flickr': 60,
#    'whatsapp': 60,

# Cryptocurrency
#    'localbitcoin': 70,
#    'poloniex': 60,
#    'coinhive': 70,
#    'bithumb': 60,
#    'kraken': 50, # some false positives
#    'bitstamp': 60,
#    'bittrex': 60,
#    'blockchain': 70,
#    'bitflyer': 60,
#    'coinbase': 60,
#    'hitbtc': 60,
#    'lakebtc': 60,
#    'bitfinex': 60,
#    'bitconnect': 60,
#    'coinsbank': 60,

# Bank/money
#    'paypal': 70,
#    'moneygram': 60,
#    'westernunion': 60,
#    'bankofamerica': 60,
#    'wellsfargo': 60,
#    'citigroup': 60,
#    'santander': 60,
#    'morganstanley': 60,
#    'barclays': 50,
#    'hsbc': 50,
#    'scottrade': 60,
#    'ameritrade': 60,
#    'merilledge': 60,
#    'bank': 15,

# Ecommerce
#    'amazon': 60,
#    'overstock': 60,
#    'alibaba': 60,
#    'aliexpress': 60,
#    'leboncoin': 70,

# Swedish governmental domains
    'aklagare': 70,
    'arbetsformedlingen': 70,
    'arbetsgivarverket': 70,
    'arkdes.se': 40,
    'arn.se': 40,
    'arvsfonden': 60,
    'av.se': 40,
    'barnombudsmannen': 70,
    'bfn.se': 40,
    'bolagsverket': 70,
    'boverket': 60,
    'bra.se': 40,
    'brottsoffermyndigheten': 70,
    'bth.se': 40,
    'cepn.se': 40,
    'csn.se': 40,
    'datainspektionen': 70,
    'dom.se': 40,
    'domstol': 60,
    'do.se': 40,
    'du.se': 40,
    'ehalsomyndigheten': 70,
    'ei.se': 40,
    'ekn.se': 40,
    'ekobrottsmyndigheten': 70,
    'elegnamnden': 70,
    'elsakerhetsverket': 70,
    'energimarknadsinspektionen': 70,
    'energimyndigheten': 70,
    'epn.se': 40,
    'esf.se': 40,
    'esv.se': 40,
    'fba.se': 40,
    'fhs.se': 40,
    'finanspolitiskaradet': 70,
    'fi.se': 40,
    'fmi.se': 40,
    'fmv.se': 40,
    'foi.se': 40,
    'folkhalsomyndigheten': 70,
    'formas.se': 60,
    'forsakringskassan': 70,
    'forskarskattenamnden': 70,
    'forsvarsmakten': 70,
    'forte.se': 40,
    'fortifikationsverket': 70,
    'fortv.se': 40,
    'fra.se': 40,
    'genteknik': 60,
    'gih.se': 40,
    'gu.se': 40,
    'han.se': 40, # Some false positives e.g. batuhan.servermerkezi.com
    'harpsund': 60,
    'havkom.se': 40,
    'havochvatten': 60,
    'hb.se': 40,
    'hh.se': 40,
    'hig.se': 40,
    'his.se': 40,
    'hkr.se': 40,
    'hsan.se': 40,
    'hv.se': 40,
    'iaf.se': 40,
    'ifau.se': 40,
    'ifau.uu.se': 60,
    'inspsf.se': 60,
    'irf.se': 40,
    'isp.se': 40,
    'ivo.se': 40,
    'jk.se': 40,
    'jordbruksverket': 70,
    'kammarkollegiet': 70,
    'kammarrattenisundsvall': 70,
    'karnavfallsfonden': 70,
    'kau.se': 40,
    'kavlinge': 60,
    'kb.se': 40,
    'kemi.se': 60,
    'ki.se': 20, # Some false positives for e.g. wiki.
    'Karolinska': 60,
    'kkh.se': 40,
    'kkv.se': 40,
    'kmh.se': 40,
    'kommers.se': 40,
    'konj.se': 40,
    'konkurrensverket': 70,
    'konstfack': 60,
    'konstnarsnamnden': 70,
    'konsumentverket': 70,
    'kriminalvarden': 70,
    'kronofogden': 70,
    'kth.se': 40,
    'kulturanalys': 60,
    'kulturradet': 60,
    'kustbevakningen': 70,
    'lagradet': 60,
    'lakemedelsverket': 70,
    'lansstyrelsen': 70,
    'lantmateriet': 70,
    'levandehistoria': 60,
    'linneuniversitetet': 70,
    'liu.se': 40,
    'livsmedelsverket': 70,
    'lnu.se': 40,
    'lotteriinspektionen': 70,
    'lsh.se': 40,
    'ltu.se': 40,
    'lu.se': 40,
    'mah.se': 40,
    'maritima': 40,
    'mdh.se': 40,
    'mfd.se': 40,
    'mfof.se': 40,
    'migrationsverket': 70,
    'mil.se': 40,
    'mi.se': 40, # Some false positives e.g. leumi.sendrineapp.net
    'miun.se': 40,
    'modernamuseet': 60,
    'mpa.se': 40,
    'mprt.se': 40,
    'msb.se': 40,
    'mtm.se': 40,
    'mucf.se': 40,
    'musikverket': 60,
    'myh.se': 40,
    'nai.se': 40,
    'namndenmotdiskriminering': 70,
    'nationalmuseum': 60,
    'naturvardsverket': 70,
    'nfh.se': 40,
    'nrm.se': 40,
    'nykoping': 60,
    'oks.se': 40,
    'onh.se': 40,
    'oru.se': 40,
    'oskarshamn': 60,
    'osthammar': 60,
    'overklagandenamnden': 70,
    'patentombudsnamnden': 70,
    'pensionsmyndigheten': 70,
    'polar.se': 60,
    'polisen': 60,
    'prv.se': 40,
    'pts.se': 40,
    'raa.se': 40,
    'radioochtv': 60,
    'rattshjalp': 60,
    'regeringen': 80,
    'regeringskansliet': 80,
    'rekryteringsmyndigheten': 70,
    'revisorsnamnden': 70,
    'riksarkivet': 70,
    'riksdagen': 80,
    'riksgalden': 60,
    'rmv.se': 40,
    'rymdstyrelsen': 70,
    'sakerhetspolisen': 80,
    'sakint': 40, # Some false positives
    'sameskolstyrelsen': 70,
    'sametinget': 60,
    'sbu.se': 40,
    'scb.se': 40,
    'sfhm.se': 40,
    'sfv.se': 40,
    'sgu.se': 40,
    'shmm.se': 40,
    'sh.se': 40,
    'sida.se': 40,
    'sieps.se': 40,
    'si.se': 40,
    'siun.se': 40,
    'skatterattsnamnden': 70,
    'skatteverket': 70,
    'skogsstyrelsen': 70,
    'skolfi.se': 60,
    'skolinspektionen': 70,
    'skolverket': 70,
    'slu.se': 40,
    'slv.se': 40,
    'smhi.se': 60,
    'snsb.se': 40,
    'socialstyrelsen': 70,
    'sprakochfolkminnen': 60,
    'spsm.se': 40,
    'spv.se': 40,
    'ssm.se': 40,
    'sst.se': 40,
    'stat.se': 40,
    'statensansvarsnamnd': 70,
    'statenskonstrad': 60,
    'statensmedierad': 60,
    'statenssc': 60,
    'stat-inst': 60,
    'statskontoret': 70,
    'stralsakerhetsmyndigheten': 70,
    'su.se': 40,
    'sunet': 60,
    'nordu': 40,
    'nordunet': 40,
    'sva.se': 40,
    'svff.se': 40,
    'swedac.se': 60,
    'swedgeo.se': 60,
    'tillvaxtanalys': 60,
    'tillvaxtverket': 60,
    'tlv.se': 40,
    'trafa.se': 40,
    'trafikverket': 70,
    'transportstyrelsen': 70,
    'tullverket': 70,
    'uhmynd.se': 40,
    'uhr.se': 40,
    'uka.se': 40,
    'umu.se': 40,
    'uniarts.se': 60,
    'upphandlingsmyndigheten': 70,
    'uu.se': 40,
    'val.se': 40, # Some false positives for saintgenislaval.senior-compagnie.fr etc
    'varberg': 40,
    'vardanalys': 60,
    'varldskulturmuseerna': 60,
    'vetansvar': 40,
    'vinnova': 40, # Some false positives for innovation etc
    'vr.se': 40,
    'vti.se': 40,

# SWAMID IdP:s
    'ADFS2.gu.se': 70,
    'adfs.rkh.se': 70,
    'adfs.umu.se': 70,
    'fs.liu.se': 70,
    'idp01.gih.se': 70,
    'idp2-1.slu.se': 70,
    'idp2.bth.se': 70,
    'idp2.his.se': 70,
    'idp2.kkh.se': 70,
    'idp3.hig.se': 70,
    'idp3.it.gu.se': 70,
    'idp3.sics.se': 70,
    'idp.antagning.se': 70,
    'idp.chalmers.se': 70,
    'idp.esh.se': 70,
    'idp.hb.se': 70,
    'idp.hh.se': 70,
    'idp.hj.se': 70,
    'idp.hkr.se': 70,
    'idp.hv.se': 70,
    'idp.it.su.se': 70,
    'idp.kb.se': 70,
    'idp.kmh.se': 70,
    'idp.kva.se': 70,
    'idp.lnu.se': 70,
    'idp.ltu.se': 70,
    'idp.mah.se': 70,
    'idp.mdh.se': 70,
    'idp.nordu.net': 70,
    'idp.qa.lnu.se': 70,
    'idpshibboleth.irf.se': 70,
    'idp.sunet.se': 70,
    'idp.ths.se': 70,
    'idp.umu.se': 70,
    'idp-v2.konstfack.se': 70,
    'idp-v2.suni.se': 70,
    'idpv3.lu.se': 70,
    'login1.fhs.se': 70,
    'login.du.se': 70,
    'login.idp.eduid.se': 70,
    'login.idp.hhs.se': 70,
    'login.it.liu.se': 70,
    'login.ki.se': 70,
    'miunidp.miun.se': 70,
    'saml.sys.kth.se': 70,
    'shibboleth.uhr.se': 70,
    'shib-idp-2.oru.se': 70,
    'siths-idp.sunet.se': 70,
    'swamid2.shh.se': 70,
    'swamid.vr.se': 70,
    'weblogin.kau.se': 70,
    'weblogin.smhi.se': 70,
    'weblogin.uu.se': 70,
    'webproxysrv.uniarts.se': 70,

# SUNET customers that are not listed in other parts
#    'chalmers': 60,
    'svenskaakademien': 60,

# Swedish governmental keywords
    'myndighet': 70,
    'myndigheten': 70,
    'departement': 70,
    'departementet': 70,
    'inspektion': 40,
    'inspektionen': 40,
    'verket': 60,
    'namnden': 60,
    'kollegiet': 70,
    'universitetet': 70,
    'hogskolan': 70,
    'kansliet': 70,
    'styrelsen': 70,
    'landsting': 60,
    'kommun': 40,

# Other Swedish keywords
    'sweden': 30,
    'sverige': 30,
    'stockholm': 40,
    'goteborg': 40,
    'svt.se': 40,
    'sverigesradio': 40,
    'mil.se': 40,
    'dinsakerhet': 60,
    'informationssakerhet': 60,
    'krisinformation': 60,
    'forsvaret': 60,
    'hemvarnet': 60,
    'tjugofyra7': 60,
    'netnod': 40,
    'aftonbladet': 40,
    'expressen': 40,
    'svd.se': 40,
    'dn.se': 40,
    'bankid': 40,
    'inloggning': 40,
    'epost': 20,
    'e-post': 20,

# Other
#    'netflix': 70,
#    'skype': 60,
#    'github': 60,
#    'onedrive': 60,
#    'dropbox': 60,

# Miscellaneous & SE tricks
    'cgi-bin': 50,
    '.com-': 20,
    '-com.': 20,
    '.se-': 50,
    '-se.': 50,
    '.se.': 50,
    '.net-': 20,
    '.org-': 20,
    '.com-': 20,
    '.net.': 20,
    '.org.': 20,
    '.com.': 20,
    '.gov-': 30,
    '.gov.': 30,
# FR specific
#    '.gouv-': 40,
#    '-gouv-': 40,
#    '.gouv.': 40,
#    'suivi': 50,
#    'laposte': 50,
}

tlds = [
    '.ga',
    '.gq',
    '.ml',
    '.cf',
    '.tk',
    '.xyz',
    '.pw',
    '.cc',
    '.club',
    '.work',
    '.top',
    '.support',
    '.bank',
    '.info',
    '.study',
    '.party',
    '.click',
    '.country',
    '.stream',
    '.gdn',
    '.mom',
    '.xin',
    '.kim',
    '.men',
    '.loan',
    '.download',
    '.racing',
    '.online',
    '.center',
    '.ren',
    '.gb',
    '.win',
    '.review',
    '.vip',
    '.party',
    '.tech',
    '.science',
    '.business'
]
